name: Reusable Build/Test/Veristat workflow

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      toolchain_full:
        required: true
        type: string
      toolchain:
        required: true
        type: string
      runs_on:
        required: true
        type: string
      llvm-version:
        required: true
        type: string
      kernel:
        required: true
        type: string
      tests:
        required: true
        type: string
      veristat_runs_on:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true

jobs:
  # Build kernel and selftest
  build:
    uses: ./.github/workflows/kernel-build.yml
    with:
      arch: ${{ inputs.arch }}
      toolchain_full: ${{ inputs.toolchain_full }}
      toolchain: ${{ inputs.toolchain }}
      runs_on: ${{ inputs.runs_on }}
      llvm-version: ${{ inputs.llvm-version }}
      kernel: ${{ inputs.kernel }}

  test:
    uses: ./.github/workflows/kernel-test.yml
    needs: [build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.tests) }}
    with:
      arch: ${{ inputs.arch }}
      toolchain_full: ${{ inputs.toolchain_full }}
      runs_on: ${{ inputs.runs_on }}
      kernel: ${{ inputs.kernel }}
      test: ${{ matrix.test }}
      continue_on_error: ${{ toJSON(matrix.continue_on_error) }}
      timeout_minutes: ${{ matrix.timeout_minutes }}

  veristat:
    if: ${{ inputs.arch == 'x86_64' &&  inputs.toolchain  == 'gcc' }}
    uses: ./.github/workflows/kernel-veristat.yml
    needs: [build]
    permissions:
      id-token: write
      contents: read
    with:
      arch: ${{ inputs.arch }}
      toolchain: ${{ inputs.toolchain }}
      aws_region: ${{ vars.AWS_REGION }}
      runs_on: ${{ inputs.veristat_runs_on }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}