name: Reusable test workflow

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      toolchain_full:
        required: true
        type: string
      runs_on:
        required: true
        type: string
      kernel:
        required: true
        type: string
      test:
        required: true
        type: string
      continue_on_error:
        required: true
        type: string
      timeout_minutes:
        required: true
        type: number

jobs:
  test:
    if: ${{ github.event_name != 'push' }}
    name: ${{ inputs.test }} on ${{ inputs.arch }} with ${{ inputs.toolchain_full }}
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    timeout-minutes: 100
    env:
      KERNEL: ${{ inputs.kernel }}
      REPO_ROOT: ${{ github.workspace }}
      REPO_PATH: ""
      KBUILD_OUTPUT: kbuild-output/
      # https://github.com/actions/runner/issues/1483#issuecomment-1031671517
      # booleans are weird in GH.
      CONTINUE_ON_ERROR: ${{ inputs.continue_on_error }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: vmlinux-${{ inputs.arch }}-${{ inputs.toolchain_full }}
          path: .
      - name: Untar artifacts
        # zstd is installed by default in the runner images.
        run: zstd -d -T0  vmlinux-${{ inputs.arch }}-${{ inputs.toolchain_full }}.tar.zst --stdout | tar -xf -
      - name: Prepare rootfs
        uses: libbpf/ci/prepare-rootfs@main
        with:
          project-name: 'libbpf'
          arch: ${{ inputs.arch }}
          kernel: ${{ inputs.kernel }}
          kernel-root: '.'
          kbuild-output: ${{ env.KBUILD_OUTPUT }}
          image-output: '/tmp/root.img'
          test: ${{ inputs.test }}
      - name: Run selftests
        uses: libbpf/ci/run-qemu@main
        # https://github.com/actions/runner/issues/1483#issuecomment-1031671517
        # booleans are weird in GH.
        continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
        timeout-minutes: ${{ inputs.timeout_minutes }}
        with:
          arch: ${{ inputs.arch}}
          img: '/tmp/root.img'
          vmlinuz: '${{ github.workspace }}/vmlinuz'
          kernel-root: '.'
          max-cpu: 8
          kernel-test: ${{ inputs.test }}