permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

on:
  pull_request:

jobs:
  pr-comment-test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout CI code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github
            ci

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.KP_REVIEW_BOT_APP_ID }}
          private-key: ${{ secrets.KP_REVIEW_BOT_APP_PRIVATE_KEY }}

      - name: Check review-inline.txt
        id: check_review
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/foo/bar/review-inline.txt
          echo ">> This is a clean performance optimization" > ${{ github.workspace }}/foo/bar/review-inline.txt
          review_file=$(find ${{ github.workspace }} -name review-inline.txt)
          cat $review_file
          echo "review_file=$review_file" >> $GITHUB_OUTPUT

      - name: Comment on PR with review results
        if: steps.check_review.outputs.review_file != ''
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const reviewContent = fs.readFileSync('${{ steps.check_review.outputs.review_file }}', 'utf8');
            const jobSummaryUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            const commentBody = `Job summary: ${jobSummaryUrl}
Review contents:
\`\`\`
${reviewContent}
\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Fail job if review file exists
        if: steps.check_review.outputs.review_file != ''
        run: |
          echo "Review file found - failing the CI job"
          exit 42

